### ISSUE TITLE
Find a way to render into properties of feathers components.

### ISSUE THREAD

**Issue by back2dos** [MVCoconut/coconut.feathersui#6]
Use case described here: https://community.haxe.org/t/feathersui-backend-for-coconut-ui/2666/37

This requires a bunch of steps:

1. generate reflection-free node types for each feathers component
2. add special case for display objects that makes RenderResult attributes which are properly rendered/updated (events can be treated via a similar special case)

**Comment by back2dos** [comment]
I'm making a bit of progress here, but I need to sort out how exactly children work in feathers. I've read up on [containers](https://feathersui.com/learn/haxe-openfl/layouts-and-containers/) and browsed the code a bit, so I have a few questions for @joshtynjala

- Most components are not containers and so one should not add arbitrary children to them. Those that have a `@defaultXmlProperty` should have the "child markup" fed into that property, e.g. what you've attempted in the post linked above should ideally read as `<FormItem text="User Name"><TextInput prompt="hello@example.com"/></FormItem>`, right?
- Are "simple containers" the only components that can have *arbitrary* children?

I've also seen there are data containers, but I think for now they'll have to be treated like normal controls and a more ergonomic integration can still be done later.

**Comment by joshtynjala** [comment]
> Those that have a @defaultXmlProperty should have the "child markup" fed into that property

Yeah, I added `@defaultXmlProperty` to define what property should be used to handle children of the XML element. It is intended for an MXML-like environment (I have a background in Adobe Flex, and I have previously offered MXML support in the Starling version of Feathers UI, so I eventually want to support the same in the Haxe version). However, I don't see why coconut.feathersui cannot make use of this metadata too.

I am also willing to add more metadata, specifically for coconut.feathersui. Please let me know if there's anything that I could expose that would help you.

> Most components are not containers and so one should not add arbitrary children to them.
> Are "simple containers" the only components that can have arbitrary children?

Correct. Most Feathers UI components should not have arbitrary children added to them. `LayoutGroup`, `ScrollContainer`, and their subclasses (such as `Panel`) can be treated as having arbitrary children.

I also recently added `HDividedBox` and `VDividedBox` too. I don't think I've added those to the "simple containers" section of the docs yet.

> e.g. what you've attempted in the post linked above should ideally read as <FormItem text="User Name"><TextInput prompt="hello@example.com"/></FormItem>, right?

Yes, this would be even better than what I originally posted. If you can detect that the property is of type `DisplayObject` (or a subclass of `DisplayObject`), and enforce only one child in the markup, that would be pretty cool.

**Comment by joshtynjala** [comment]
Also, I just want to say thank you for looking into this!
