### ISSUE TITLE
Type not found : coconut.ui.internal.Children

### ISSUE THREAD

**Issue by hansagames** [MVCoconut/coconut.feathersui#9]
Suddenly could not compile test project with error 

`Type not found : coconut.ui.internal.Children'

@back2dos any changes have been done to `coconut.ui` ?

**Comment by back2dos** [comment]
You probably need the git HEAD of coconut.ui. Will try to make releases this week ;)

**Comment by hansagames** [comment]
Updated dependencies so should work now
